language: php

services:
  - docker

before_install:
  - docker build -t rabbitmq-testserver testserver
  - docker run -d -p 5672:5672 -p 15672:15672 rabbitmq-testserver

before_script:
  - composer install --prefer-source

php:
  - 7.2
  - 7.3

script:
  - vendor/bin/phpunit
