FROM rabbitmq:3.8.0-rc.1-management
COPY rabbitmq.conf /etc/rabbitmq/


# run me with:
# docker build -f Dockerfile -t rabbitmq-test-server
# docker run -p 5672:5672 -p 15672:15672 --name rabbitmq-test-server rabbitmq-test-server

# warning, those ports will be open on the local machine with default guest/guest username/password
# this is for testing only



